version: 2.1

jobs:
  build:
     docker:
      - image: circleci/node:8
     steps:
      - checkout
      - run: echo "Hello world"
  build-storybook:
     docker:
      - image: circleci/node:8
     steps:
      - run: echo "Hello world"
  deploy-storybook:
     docker:
      - image: circleci/node:8
     steps:
      - run: echo "Hello world"


workflows:
  version: 2
  deploy-storybook:
    jobs:
      - build-storybook
      - approval:
          type: approval
          requires: 
            - build-storybook
      - deploy-storybook:
          requires: 
            - approval
  main:
    jobs:
      - build
