version: 2.1

jobs:
  deploy-storybook:
     docker:
      - image: circleci/node:8
     steps:
      - checkout
      - run: echo "Hello world"


workflows:
  version: 2
  main:
    jobs:
      - deploy-storybook
